[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    h2zero/NimBLE-Arduino@1.4.3
build_flags =
    -D RELAY_AP_SSID=\"smoker-relay\"
    -D RELAY_AP_PASS=\"nxe-relay-32\"
    -D RELAY_STA_SSID=\"\"
    -D RELAY_STA_PASS=\"\"
    -D RELAY_HTTP_PORT=80
